# permissions for end users to edit cosmosfullnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cosmosfullnode-editor-role
rules:
- apiGroups:
  - cosmos.b.harvest
  resources:
  - cosmosfullnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cosmos.b.harvest
  resources:
  - cosmosfullnodes/status
  verbs:
  - get
