---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cosmos.b.harvest
  resources:
  - cosmosfullnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cosmos.b.harvest
  resources:
  - cosmosfullnodes/finalizers
  verbs:
  - update
- apiGroups:
  - cosmos.b.harvest
  resources:
  - cosmosfullnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cosmos.b.harvest
  resources:
  - scheduledvolumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cosmos.b.harvest
  resources:
  - scheduledvolumesnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - cosmos.b.harvest
  resources:
  - scheduledvolumesnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cosmos.b.harvest
  resources:
  - statefuljobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cosmos.b.harvest
  resources:
  - statefuljobs/finalizers
  verbs:
  - update
- apiGroups:
  - cosmos.b.harvest
  resources:
  - statefuljobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - watch
